apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: confighub/confighub-worker
  annotations:
    confighub.com/BridgeWorkerID: 9d26ef28-f3bb-4b26-b2dc-e90c7e942451
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|confighub|confighub-worker'
  name: confighub-worker
  namespace: confighub
