apiVersion: v1
data:
  CONFIGHUB_URL: http://127.0.0.1:9090
  CONFIGHUB_WORKER_HTTP_SERVER_PORT: "9092"
  configHub.configName: ConfigHubWorker
  configHub.configSchema: ConfigHubWorker
kind: ConfigMap
metadata:
  annotations:
    confighub.com/BridgeWorkerID: 9d26ef28-f3bb-4b26-b2dc-e90c7e942451
    installer.confighub.com/appconfig-mode: env
    installer.confighub.com/appconfig-mutable: "true"
    installer.confighub.com/toolchain: AppConfig/Env
  name: confighub-worker-env
  namespace: confighub
